### ISSUE TITLE
数据加载不出来

### ISSUE THREAD

**Issue by yb12306** [SmileZXLee/ZXPagingScrollView#4]
网络请求数据完成以后，我tableview为啥数据没法渲染出来呢

**Comment by SmileZXLee** [comment]
您好，请提供可复现的demo或加入qq群790460711交流，以便我排查问题，感谢。

**Comment by yb12306** [comment]
已解决，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SmileZXLee/ZXPagingScrollView"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月8日(星期二) 上午9:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SmileZXLee/ZXPagingScrollView] 数据加载不出来 (Issue #4)





 
您好，请提供可复现的demo或加入qq群790460711交流，以便我排查问题，感谢。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
